title: Thijs Laarhoven
position: Research Scientist @ <a href='https://tno.nl'>TNO</a>
affiliation: Eindhoven, The Netherlands
email: mail (at) thijs.com
keywords: minimal academic
google_scholar: https://scholar.google.nl/citations?user=lLqnszIAAAAJ
github_link: https://github.com/tmmlaarhoven/
linkedin: https://www.linkedin.com/in/tmmlaarhoven/
avatar: ./assets/img/thijs-small.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Thijs' homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
